"""add repositories

Revision ID: 04d31c580568
Revises: 5383c9ffd585
Create Date: 2026-06-07 17:54:02.374622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d31c580568'
down_revision: Union[str, Sequence[str], None] = '5383c9ffd585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_chat_id'), 'documents', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_chat_id'), table_name='documents')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    # ### end Alembic commands ###
