"""vector can be nullable for now

Revision ID: 5383c9ffd585
Revises: 1cf66463d97f
Create Date: 2026-06-03 20:42:19.899996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '5383c9ffd585'
down_revision: Union[str, Sequence[str], None] = '1cf66463d97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=VECTOR(dim=384),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=VECTOR(dim=384),
               nullable=False)
    # ### end Alembic commands ###
