"""update document chunk vector to 768

Revision ID: f0798b559d4d
Revises: b8f402aae1a0
Create Date: 2026-06-07 19:41:05.923709

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0798b559d4d'
down_revision: Union[str, Sequence[str], None] = 'b8f402aae1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=VECTOR(dim=384),
               type_=VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=VECTOR(dim=768),
               type_=VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###
